services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: mnist_webapp
    ports:
      - "5000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
